module/core:
  - core/**/*

module/app:
  - app/**/*

module/desktop:
  - desktop_app/**/*
  
circleci:
  - .circleci/**/*

github:
  - .github/**/*

gradle:
  - gradle/**/*
  - */**/*.gradle
  - */**/*.gradle.kts
  - buildSrc/**/*
  - build-scripts/**/*
  - gradle.properties
  
java:
  - */**/src/main/java/*.java
