module/core:
  - core/**/*

module/app:
  - app/**/*
  
module/desktop:
  - desktop_app/**/*
  
circleci:
  - .circleci/**/*

github:
  - .github/**/*

gradle:
  - gradle/**/*
  - */**/*.gradle
  - */**/*.gradle.kts
  - buildSrc/**/*
  - build-scripts/**/*
  - gradle.properties
  
#java1:
#  - */**/src/main/java/*

#java2:
#  - */**/src/main/java/*.java
  
#java3:
#  - **/src/main/java/*
  
#java4:
#  - ./**/src/main/java/*
  
#java5:
#  - **/src/main/java/*.java

