'.circleci/**':
  - maxirosson
'.github/**':
  - giacomuzzi
'build-scripts/**':
  - giacomuzzi
'buildSrc/**':
  - giacomuzzi
'scripts':
  - giacomuzzi
'*.gradle':
  - giacomuzzi
'*.gradle.kts':
  - giacomuzzi
'.gitignore':
  - giacomuzzi
'**/.gitignore':
  - giacomuzzi

