version: 2.1

parameters:
  api:
    type: boolean
    default: false
  run_integration_tests:
    type: boolean
    default: false

references:

  ## Workspace

  workspace: &workspace
    ~/job_workspace

  ## Docker image configurations

  android_config: &android_config
    working_directory: *workspace
    docker:
      - image: circleci/android:api-29
    environment:
      JVM_OPTS: -Xmx3200m
      GRADLE_OPTS: -Dorg.gradle.caching=true -Dorg.gradle.parallel=true -Dorg.gradle.jvmargs="-Xmx4g -Xms1g"
      A: a
      B: b
      sonar.projectKey: maxirosson_sample

  android_config_large: &android_config_large
    <<: *android_config
    environment:
      C: c

orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.1

jobs:

  jobA0:
    <<: *android_config_large
    steps:
      - checkout
      - run:
          command: |
            echo $c

  jobA1:
    <<: *android_config
    steps:
      - checkout
      - run:
          name: Setup Environment Variables
          command: |
            echo "export B=BJob" >> $BASH_ENV
            echo "export C=CJob" >> $BASH_ENV
      - run: |
          echo $A
          echo $B
          echo $C
      - run: |
          mkdir aaa
          cd aaa
          mkdir bbb
          cd bbb
          echo "hello jobA1" > a1.txt
      - persist_to_workspace:
          root: ./aaa
          paths:
            - bbb/a1.txt
      - run: |
          mkdir ccc
          cd ccc
          echo "hello jobA1 inner 1" > a1_inner1.txt
          echo "hello jobA1 inner 2" > a1_inner2.txt
      - persist_to_workspace:
          root: .
          paths:
            - ccc
      - run: |
          mkdir build
          cd build
          echo "class1.java" > class1.java
          echo "class2.java" > class2.java
      - persist_to_workspace:
          root: .
          paths:
            - build
  jobA2:
    <<: *android_config
    steps:
      - checkout
      - run: |
          mkdir ccc
          cd ccc
          echo "hello jobA2 inner 1" > a2_inner1.txt
          echo "hello jobA2 inner 2" > a2_inner2.txt
      - persist_to_workspace:
          root: .
          paths:
            - ccc

  jobB:
    <<: *android_config
    steps:
      - run: pwd
      - run: |
          mkdir ccc
          cd ccc
          echo "hello inner 3" > a1_inner3.txt
      - attach_workspace:
          at: ./workspace
      - run: find . | sed -e "s/[^-][^\/]*\// |/g" -e "s/|\([^ ]\)/|-\1/"
      - run: cat ./workspace/bbb/a1.txt
      - run: echo "hello jobB" > ./workspace/bbb/b1.txt
      - persist_to_workspace:
          root: ./workspace
          paths:
            - bbb/b1.txt
      - run: |
          mkdir build
          cd build
          echo "class1.java" > class1.java
          echo "class3.java" > class3.java
      - persist_to_workspace:
          root: .
          paths:
            - build

  jobC:
    <<: *android_config
    steps:
      - attach_workspace:
          at: ./workspace
      - run: find . | sed -e "s/[^-][^\/]*\// |/g" -e "s/|\([^ ]\)/|-\1/"
      - run: cat ./workspace/bbb/a1.txt
      - run: cat ./workspace/bbb/b1.txt

  mytestjob:
    <<: *android_config
    steps:
      - checkout
      - run: echo "my test job"

  sonar:
    <<: *android_config
    steps:
      - checkout
      #- run: ./gradlew clean testDebugUnitTest jacocoTestReport sonarqube -Psonar.pullrequest.branch=${CIRCLE_BRANCH} --stacktrace
      - run: ./gradlew clean testDebugUnitTest jacocoTestReport --stacktrace
      - sonarcloud/scan

workflows:
  commit:
    unless: << pipeline.parameters.api >>
    jobs:
      - sonar
      - jobA0
      - jobA1
      - jobA2
      - jobB:
          requires:
            - jobA1
            - jobA2
      - jobC:
          requires:
            - jobB
  integration_tests:
    when: << pipeline.parameters.run_integration_tests >>
    jobs:
      - mytestjob
