version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "build.gradle" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: gradle dependencies
      - run: gradle assemble
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}

  test:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run: gradle test
      - store_artifacts:
          path: ./core/build/reports/tests
          
  verify:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run: echo "Checking code quality on each commit......."

  verify_nightly:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run: echo "Checking code quality on nightly......."
      
  deploy:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run: echo "Deploying sample ......."
  
workflows:
  version: 2
  commit:
    jobs:
      - build
      - test:
          requires:
            - build
      - verify:
          requires:
            - build    
      - deploy:
          requires:
            - test
            - verify
          filters:
            branches:
              only:
                - master
                - production
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - verify_nightly
