defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/openjdk:8-jdk
  environment:
    # Customize the JVM maximum heap limit
    JVM_OPTS: -Xmx3200m
    TERM: dumb
version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "build.gradle" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: gradle dependencies
      - run: gradle assemble
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}

  test:
    <<: *defaults
    steps:
      - checkout
      - run: gradle test
      - run:
          name: Save test results 
          command: |
            mkdir -p ~/junit/
            find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/junit/ \;
          when: always
      - store_test_results:
          path: ~/junit
      - store_artifacts:
          path: ~/junit
          
  verify:
    <<: *defaults
    steps:
      - checkout
      - run: echo "Checking code quality on each commit......."

  verify_nightly:
    <<: *defaults
    steps:
      - checkout
      - run: echo "Checking code quality on nightly......."
      
  deploy:
    <<: *defaults
    steps:
      - checkout
      - run: echo "Deploying sample ......."
  
workflows:
  version: 2
  commit:
    jobs:
      - build
      - test:
          requires:
            - build
      - verify:
          requires:
            - build    
      - deploy:
          requires:
            - test
            - verify
          filters:
            branches:
              only:
                - master
                - production
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - verify_nightly
