version: 2

references:

  ## Workspace

  workspace: &workspace
    ~/workspace

  ## Cache

  cache_key: &cache_key
    key: cache-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}-{{ checksum "build.gradle" }}-{{ checksum "core/build.gradle" }}
  restore_cache: &restore_cache
    restore_cache:
      <<: *cache_key
  save_cache: &save_cache
    save_cache:
      <<: *cache_key
      paths:
        - ~/.gradle
        - ~/.m2

  ## Docker image configurations

  android_config: &android_config
    working_directory: *workspace
    docker:
      - image: circleci/android:api-28
    environment:
      JVM_OPTS: -Xmx3200m
      GRADLE_OPTS: -Dorg.gradle.caching=true -Dorg.gradle.daemon=false -Dorg.gradle.parallel=false -Dorg.gradle.jvmargs="-Xmx4g -Xms1g"

jobs:
  build:
    <<: *android_config
    steps:
      - checkout
      - run: echo "Hello"

  apiJob:
      <<: *android_config
      steps:
        - checkout
        - run: echo "Hello ${PARAM_1}"

  hold:
      <<: *android_config
      steps:
        - checkout
        - run: echo "Hello world approved"

  upgradeDependencies:
    <<: *android_config
    steps:
      - checkout
      - run:
          name: Upgrade Dependencies
          command: ./gradlew upgradeDependencies -PpullRequestEnabled=true --stacktrace

workflows:
  version: 2
  commit:
    jobs:
      - build