version: 2

references:

  ## Workspace

  workspace: &workspace
    ~/job_workspace

  ## Docker image configurations

  android_config: &android_config
    working_directory: *workspace
    docker:
      - image: circleci/openjdk:8-jdk
    environment:
      JVM_OPTS: -Xmx3200m
      GRADLE_OPTS: -Dorg.gradle.caching=true -Dorg.gradle.parallel=true -Dorg.gradle.jvmargs="-Xmx4g -Xms1g"

jobs:

  jobA1:
    <<: *android_config
    steps:
      - checkout
      - run: pwd

  jobA2:
    <<: *android_config
    steps:
      - checkout
      - run: pwd

  jobB:
    <<: *android_config
    steps:
      - checkout
      - run: pwd

workflows:
  version: 2
  commit:
    jobs:
      - jobA1
      - jobA2
      - jobB:
          requires:
            - jobA1
            - jobA2