version: 2.1

parameters:
  api:
    type: boolean
    default: false
    
  upgradeDependencies:
    type: boolean
    default: false
    
  jobCacheKey:
    type: string
    default: v1-jobcache

references:

  ## Workspace

  workspace: &workspace
    ~/project

executors:
  android_executor:
    working_directory: *workspace
    docker:
      - image: circleci/android:api-29
    environment:
      JVM_OPTS: -Xmx3200m
      GRADLE_OPTS: -Dorg.gradle.caching=true -Dorg.gradle.parallel=true -Dorg.gradle.jvmargs="-Xmx4g -Xms1g"

jobs:

  a1:
    executor: android_executor
    steps:
      - checkout
      - run:
          name: "Vars"
          command: |
            echo "Pipeline id: << pipeline.id >>"
            echo "Pipeline number: << pipeline.number >>"
            echo "Workflow id: $CIRCLE_WORKFLOW_ID"
            echo "Workflow id: {{ .Environment.workflow }}"
      - run:
          name: "Create artifact to cache"
          command: echo "<< pipeline.id >>-$CIRCLE_WORKFLOW_ID" > a1.txt

  upgradeDependencies:
    executor: android_executor
    steps:
      - checkout
      - run:
          name: Upgrade Dependencies
          command: ./gradlew upgradeDependencies --stacktrace
          
workflows:
  commit:
    jobs:
      - a1:
      - publish:
          requires:
            - a2
            
  upgradeDependencies:
    when: << pipeline.parameters.upgradeDependencies >>
    jobs:
      - upgradeDependencies
