version: 2

references:

  ## Workspace

  workspace: &workspace
    ~/workspace

  ## Cache

  cache_key: &cache_key
    key: v1-cache-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
  restore_gradle_cache: &restore_gradle_cache
    restore_cache:
      <<: *cache_key
  save_gradle_cache: &save_gradle_cache
    save_cache:
      <<: *cache_key
      paths:
        - ~/.gradle
        - ~/.m2
    run:
      name: Clean Build Cache
      command: rm -rf ~/.gradle/caches/build-cache-*

  ## Docker image configurations

  android_config: &android_config
    working_directory: *workspace
    docker:
      - image: circleci/android:api-28
    environment:
      JVM_OPTS: -Xmx3200m
      GRADLE_OPTS: -Dorg.gradle.caching=true -Dorg.gradle.parallel=true -Dorg.gradle.jvmargs="-Xmx4g -Xms1g"

jobs:

  gradleCache:
    <<: *android_config
    resource_class: large
    steps:
      - checkout
      - *restore_gradle_cache
      - run:
          name: Download dependencies
          command: ./gradlew dependencies --stacktrace
      - *save_gradle_cache
      -
  buildCore:
    <<: *android_config
    steps:
      - checkout
      - run: ./gradlew :core:assemble

  buildApp:
    <<: *android_config
    steps:
      - checkout
      - run: ./gradlew :app:assemble

  apiJob:
      <<: *android_config
      steps:
        - checkout
        - run: echo "Hello ${PARAM_1}"

  hold:
      <<: *android_config
      steps:
        - checkout
        - run: echo "Hello world approved"

  upgradeDependencies:
    <<: *android_config
    steps:
      - checkout
      - run:
          name: Upgrade Dependencies
          command: ./gradlew upgradeDependencies -PpullRequestEnabled=true --stacktrace

workflows:
  version: 2
  commit:
    jobs:
      - gradleCache
      - buildCore:
          requires:
            - gradleCache
      - buildApp:
          requires:
            - buildCore