version: 2

references:

  ## Workspace

  workspace: &workspace
    ~/job_workspace

  ## Docker image configurations

  android_config: &android_config
    working_directory: *workspace
    docker:
      - image: circleci/openjdk:8-jdk
    environment:
      JVM_OPTS: -Xmx3200m
      GRADLE_OPTS: -Dorg.gradle.caching=true -Dorg.gradle.parallel=true -Dorg.gradle.jvmargs="-Xmx4g -Xms1g"

jobs:

  jobA1:
    <<: *android_config
    steps:
      - checkout
      - run: pwd
      - run: |
          mkdir aaa
          cd aaa
          mkdir bbb
          cd bbb
          echo "hello jobA1" > a1.txt
      - persist_to_workspace:
          root: ./aaa
          paths:
            - bbb/a1.txt
      - run: |
          mkdir ccc
          cd ccc
          echo "hello jobA1 inner 1" > a1_inner1.txt
          echo "hello jobA1 inner 2" > a1_inner2.txt
      - persist_to_workspace:
          root: .
          paths:
            - ccc

  jobA2:
    <<: *android_config
    steps:
      - checkout
      - run: |
          pwd
          cd ~
          ls -l

  jobB:
    <<: *android_config
    steps:
      - checkout
      - run: pwd
      - attach_workspace:
          at: ./workspace
      - run: find . | sed -e "s/[^-][^\/]*\// |/g" -e "s/|\([^ ]\)/|-\1/"
      - run: cat ./workspace/bbb/a1.txt
      - run: echo "hello jobB" > ./workspace/bbb/b1.txt
      - persist_to_workspace:
          root: ./workspace
          paths:
            - bbb/b1.txt

  jobC:
    <<: *android_config
    steps:
      - checkout
      - attach_workspace:
          at: ./workspace
      - run: cat ./workspace/bbb/a1.txt
      - run: cat ./workspace/bbb/b1.txt

workflows:
  version: 2
  commit:
    jobs:
      - jobA1
      - jobA2
      - jobB:
          requires:
            - jobA1
            - jobA2
      - jobC:
          requires:
            - jobB