name: Test Action
on:
  workflow_dispatch:

jobs:
  testAction:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - uses: convictional/trigger-workflow-and-wait@v1.5.0
        with:
          owner: maxirosson
          repo: sample
          github_token: ${{ secrets.CI_GITHUB_WRITE_TOKEN }}
          workflow_file_name: main.yml
          ref: master
          inputs: '{"param1":"${GITHUB_REF#refs/*/}"}'
