name: Emerge Generate Baseline Profile

on:
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    env:
      EMERGE_API_TOKEN: ${{ secrets.EMERGE_API_TOKEN }}

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
#      - name: Generate Baseline Profile
#        run: ./gradlew emergeGenerateReleaseBaselineProfile
#        env:
#          EMERGE_API_TOKEN: ${{ secrets.EMERGE_API_TOKEN }}
      - name: Download Baseline Profile
        run: |
          $API_URL = ${{ secrets.URL }}
          
          # After 10 minutes, we call Emerge API
          #sleep 10m
          RESPONSE=$(curl $API_URL --header "X-API-Token: ${{ secrets.EMERGE_API_TOKEN }}" --fail)
          
          # We get the generated baseline profile url from the API response (url key on the json)
          PROFILE_URL=$(echo "$RESPONSE" | jq -r ".url")
          
          # Download the generated baseline profile and store it into src/main/ of your app module
          APP_PROJECT_PATH="app"
          PROFILE_PATH="$APP_PROJECT_PATH/src/main/baseline-profile.txt"
          curl -o $PROFILE_PATH $PROFILE_URL --fail
        env:
          URL: ${{ secrets.URL }}
      # Create a PR with the generated baseline profile, using https://github.com/marketplace/actions/create-pull-request
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          branch: "emerge/baseline_profile"
          title: "Updated Baseline Profile"
          body: "Automated changes by Emerge Generate Baseline Profile Github Action"
