name: 'Merge command'

on: issue_comment

jobs:
  merge-command:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Merge command
        # https://github.com/marketplace/actions/automatic-merge
        uses: lots0logs/gh-action-auto-merge@1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}