name: Template Workflow

on:
  workflow_call:
  
jobs:
  template-job1:
    runs-on: ubuntu-latest
    steps:
      - name: Step
        run: echo "Template workflow job 1"
  template-job2:
    runs-on: ubuntu-latest
    steps:
      - name: Step
        run: echo "Template workflow job 2"
