name: Test Environment

on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Echo
        run: |
         echo "Hello World 1"
  job2:
    runs-on: ubuntu-latest
    #environment: test
    needs: job1
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Install dependencies
        run: npm install
        working-directory: scripts
      - name: Tweet
        working-directory: scripts
        run: node twitter.js ${{ secrets.TWITTER_API_KEY }} ${{ secrets.TWITTER_API_KEY_SECRET }} ${{ secrets.TWITTER_ACCESS_TOKEN }} ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }} "When purchasing a hardware wallet, using Bitcoin for payment enhances privacy by minimizing the amount of personal and financial information associated with the transaction."
