name: Test Action
on:
  workflow_dispatch:

jobs:
  testAction:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Set env
        run: |
          echo "RELEASE_VERSION=111" >> $GITHUB_ENV
          echo "JSON={"param1":"${RELEASE_VERSION}"}" >> $GITHUB_ENV
      - name: Get env
        run: |
          echo ${{ env.JSON }}
      - uses: convictional/trigger-workflow-and-wait@v1.5.0
        with:
          owner: maxirosson
          repo: sample
          github_token: ${{ secrets.CI_GITHUB_WRITE_TOKEN }}
          workflow_file_name: main.yml
          ref: master
          inputs: ${{ env.JSON }}
