name: Test Environment

on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Echo
        run: |
         echo "Hello World 1"
         URL=1234
         echo "URL=${URL}" >> "$GITHUB_ENV"
  job2:
    runs-on: ubuntu-latest
    environment: 
      name: test
      url: "123456"
    needs: job1
    steps:
      - name: Echo
        run: |
         echo "Hello World 2"
