name: Test Environment

on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Echo
        run: |
         echo "Hello World 1"
  job2:
    runs-on: ubuntu-latest
    environment: test
    needs: job1
    steps:
      - name: Echo
        run: |
         echo "Hello World 2"
