name: Emerge Generate Baseline Profile

on:
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    environment: test
    steps:
      - name: Echo
        run: |
         echo "Hello World"
