name: Test Environment

on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Echo
        run: |
         echo "Hello World 1"
         echo "SAMPLE_VAR=12434" >> "$SAMPLE_VAR"

  job2:
    runs-on: ubuntu-latest
    environment: test
    env:
      TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
      TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
      TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
      TWITTER_API_KEY_SECRET: ${{ secrets.TWITTER_API_KEY_SECRET }}
      TWITTER_BEARER_TOKEN: ${{ secrets.TWITTER_BEARER_TOKEN }}
    needs: job1
    steps:
      - name: Echo
        run: |
         echo $SAMPLE_VAR
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Python
        run: |
          python3 -m venv venv
          source venv/bin/activate
      - name: Install Dependencies
        working-directory: scripts
        run: pip install -r requirements.txt
      - name: Tweet
        working-directory: scripts
        run: python3 twitter.py "When purchasing a hardware wallet, using Bitcoin for payment enhances privacy by minimizing the amount of personal and financial information associated with the transaction."
        
