name: Test Action
on:
  workflow_dispatch:

jobs:
  testAction:
    runs-on: ubuntu-latest
    steps:
      - uses: theborakompanioni/nostr-action@v1
        with:
          key: ${{ secrets.NOSTR_KEY }}
          relay: wss://feeds.nostr.band/lang/en
          content: Hello World
